realm = "ssh-demo"
endpoint = "https://keycloak.example.com"
clientid = "keycloak-client-id"
clientsecret = "MIKEcHObWmI3V3pF1hcSqC9KEILfLN"
clientscope = "openid"
clientrole = "keycloak-client-role"
proxyurl = "https://192.168.0.1:8080"